// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqkhglepzmsscyujozif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxa2hnbGVwem1zc2N5dWpvemlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDU2MjMsImV4cCI6MjA1NTU4MTYyM30.ijFq3Awey_8Hcv3BQYddxnOSNTfWQ10Zig6X4ALqAmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);